spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.39.73:3306/yuemei?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: qfjava
  mvc:  #视图解析器
      view:
        prefix: /
        suffix: .html
      server:
          port: 8080
mybatis:
  type-aliases-package: com.pinming.pojo
  mapper-locations: classpath*:/mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

